%Written 02/2024 by MRT
%Cleaned up and commented 03/2024 by SB

% MIT License
% Copyright (c) 2024 Michael R. Tadross

%Function to calculate the statistical significance of the mean difference
%between two groups

%Inputs:
%   y1: matrix, control values
%   y2: matrix, experimental values
%   yTick: two values, max and min y values of the desired plot
%   DotSize: optional; change dot size of the plot
%   NumBoot: optional; specify number of bootstrap calculations performed
%Output: beeswarm plot of the two groups with the mean and confidence interval to the right
%   uses beeswarm generated by % % Ian Stevenson, CC-BY 2019 % %
%   p-value of the mean difference and 95% confidence intervals are included in the plot


function STAT = TwoGroupsMeanDiff(y1, y2, yTick, DotSize, NumBoot)

%ALL mice
try
    %specify NumBoot
    [STAT.Fit1, STAT.Fit2, STAT.Fit2m1, STAT.MixingTest] = BootFitDifferencePlot(0, y1*0, y1, y2*0, y2, 0, NumBoot);
catch
    %use default NumBoot
    [STAT.Fit1, STAT.Fit2, STAT.Fit2m1, STAT.MixingTest] = BootFitDifferencePlot(0, y1*0, y1, y2*0, y2, 0);
end
try
    DS = DotSize;
catch
    DS = 12; %default dot size
end

cla; %clear axis
axis([-1 3 min(yTick) max(yTick)]); drawnow; hold on;

xbee = beeswarm([y1*0; y2*0+1], [y1; y2], 'use_current_axes', 1, 'dot_size', DS*1.2, 'sort_style', 'rand');
cla;

%draw axes from scratch:
for k=1:length(yTick)
    plot([-1 3],[0 0]+yTick(k),    ':k'); hold on;
    text(-1.1, yTick(k), num2str(yTick(k)), 'FontName', 'Courier', 'HorizontalAlignment', 'right');
end
plot(xbee(1:length(y1)), y1, 'o', 'markersize', DS, 'MarkerFaceColor',     [0 0 0]*0.9 + [1 1 1]*0.1, 'MarkerEdgeColor', 'none', 'MarkerEdgeColor', 'none'); hold on;
plot(xbee(length(y1)+1:end), y2, 'o', 'markersize', DS, 'MarkerFaceColor', [1 0 0]*0.9 + [1 1 1]*0.1, 'MarkerEdgeColor', 'none', 'MarkerEdgeColor', 'none'); hold on;
axis off;

GraphicMode = 2;
for j=1:length(GraphicMode)
    if abs(GraphicMode(j))==1
        %Fit2m1 mode -- for both pdf and 95CI
        [N,E] = histcounts(STAT.Fit2m1.TermDiffBoot, 30, 'Normalization', 'pdf');
        C = (E(1:end-1) + E(2:end))/2; %bin centers
        C = C + STAT.Fit1.Term; %offset relative to control
        
        CI95 = STAT.Fit1.Term + STAT.Fit2m1.TermDiffCI95;
        CImid = STAT.Fit2.Term;
        
        XPDF  = 1.8; %x-position of PDF distribution
        X95CI = 1.8; %x-position for CI
        clr1 = 'r';
        clr2 = 'k';
        
    elseif abs(GraphicMode(j))==2
        %Hybrid Mode -- PDF of Fit2m1, with 95CI of Mixing Test
        
        %pdf of Fit2m1
        [N,E] = histcounts(STAT.Fit2m1.TermDiffBoot, 30, 'Normalization', 'pdf');
        C = (E(1:end-1) + E(2:end))/2; %bin centers
        C = C + STAT.Fit1.Term; %offset relative to control
        
        %95 CI from Mixing Test
        CI95 = STAT.Fit2.Term + STAT.MixingTest.TermDiffNullCI95;
        CImid = STAT.Fit2.Term;
        
        X95CI = 1.8; %x-position for CI
        XPDF  = 2.0; %x-position of PDF distribution
        clr1 = 'r';
        clr2 = 'k';
        
    elseif abs(GraphicMode(j))==3
        %MixingTest -- for both pdf and 95CI
        [N,E] = histcounts(STAT.MixingTest.TermDiffNullBoot, 31, 'Normalization', 'pdf');
        C = (E(1:end-1) + E(2:end))/2; %bin centers
        C = C + STAT.Fit2.Term; %offset relative to positive
        CI95 = STAT.Fit2.Term + STAT.MixingTest.TermDiffNullCI95;
        CImid = STAT.Fit2.Term;
        
        X95CI = 1.8; %x-position for CI
        XPDF  = 1.8; %x-position of PDF distribution
        clr1 = 'r';
        clr2 = 'k';
    end
    %add points to start and end of histogram
    dC = mean(diff(C));
    C = [C(1)-dC C  C(end)+dC];
    N = [0 N 0];
    N = 1.5*0.3*N/max(N);
    h=patch(N + XPDF+(j-1)/1.5, C, clr1);
    set(h,'LineStyle', 'none', 'FaceAlpha', 1');
    
    %95% confidence interval and line
    plot([0 0]+X95CI+(j-1)/1.5,  CI95, clr2, 'linewidth', 5);
end
plot([1 X95CI], [0 0]+STAT.Fit2.Term, '-', 'color', 'k', 'linewidth', 1);
plot([0 XPDF+0.3], [0 0]+STAT.Fit1.Term, '-', 'color', 'k', 'linewidth', 1);
grid on;

%text on figure
text(-0.8, max(yTick), [...
    'Permutation Test:'  newline ...
    '     P = ' num2str(STAT.MixingTest.P_TermDiffVsNull) newline ...
    '     Null 95CI = (' num2str(STAT.MixingTest.TermDiffNullCI95') ')' newline ...
    'Effect Size: Mean Diff = ' num2str(STAT.Fit2m1.TermDiff) newline ...
    '     Boot 95CI = (' num2str(STAT.Fit2m1.TermDiffCI95') ')' newline  ...
    ], 'FontName', 'Courier');
